language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc

branches:
  only:
    - master
    - develop

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-catkin-pkg python-rosdep -qq
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/package
  - cd /tmp/ws/src
  - git clone https://github.com/WPI-RAIL/rail_manipulation_msgs.git
  - cd ../
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y

script:
  - source /opt/ros/hydro/setup.bash
  - catkin_make
  - catkin_make install
  - rm -rf build/ devel/ install/
  - sudo apt-get purge yaml-cpp
  - wget https://yaml-cpp.googlecode.com/files/yaml-cpp-0.5.1.tar.gz
  - tar -xvzf yaml-cpp-0.5.1.tar.gz
  - cd yaml-cpp-0.5.1/
  - mkdir build
  - cd build/
  - cmake ..
  - make
  - sudo make install
  - cd ../../
  - rm -rf yaml*
  - catkin_make
  - catkin_make install
