language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc

branches:
  only:
    - master
    - develop

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-catkin-pkg python-rosdep ros-hydro-catkin -qq
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/package
  - cd /tmp/ws/src
  - git clone https://github.com/WPI-RAIL/python_ethernet_rmp.git
  - git clone https://github.com/WPI-RAIL/battery_monitor_rmp.git
  - git clone https://github.com/WPI-RAIL/ros_ethernet_rmp.git
  - git clone https://github.com/WPI-RAIL/rmp_msgs.git
  - git clone https://github.com/WPI-RAIL/m4atx_battery_monitor.git
  - git clone https://github.com/RIVeR-Lab/wpi_jaco.git
  - git clone https://github.com/WPI-RAIL/carl_bot.git
  - cd ../
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y

script:
  - source /opt/ros/hydro/setup.bash
  - catkin_make
  - catkin_make install
