language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc

branches:
  only:
    - master
    - develop

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-catkin-pkg python-rosdep -qq
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/package
  - cd /tmp/ws/src
  - git clone https://github.com/ros-perception/perception_pcl.git -b indigo-devel
  - git clone https://github.com/ros/common_msgs.git -b indigo-devel
  - git clone https://github.com/ros/geometry_experimental.git -b indigo-devel
  - mv geometry_experimental/tf2_sensor_msgs .
  - rm -rf geometry_experimental
  - cd ../
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y

script:
  - source /opt/ros/hydro/setup.bash
  - catkin_make -j1
  - catkin_make install
