language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc

branches:
  only:
    - master
    - develop

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-catkin-pkg python-rosdep -qq
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - cd /tmp/ws/src
  - git clone https://github.com/ros-perception/perception_pcl.git
  - cd ../
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y

script:
  - source /opt/ros/hydro/setup.bash
  - catkin_make tests --source . -j1 -DCATKIN_ENABLE_TESTING=ON
  - catkin_make run_tests --source . -j1 -DCATKIN_ENABLE_TESTING=ON
  - catkin_make install --source . -j1 -DCATKIN_ENABLE_TESTING=ON
