- name: "Front Surface"
  remove_surface: true
  parent_frame_id: "base_footprint"
  child_frame_id: "camera_depth_frame"
  bounding_frame_id: "base_footprint"
  segmentation_frame_id: "map"
  roll_min: 0.00
  roll_max: 2.00
  pitch_min: 0.00
  pitch_max: 0.95
  x_min: 0.44
  x_max: 1.25
  z_min: 0.20
- name: "Base Plate"
  remove_surface: false
  parent_frame_id: "base_footprint"
  child_frame_id: "camera_depth_frame"
  bounding_frame_id: "base_footprint"
  segmentation_frame_id: "base_link"
  roll_min: 0.00
  roll_max: 2.00
  pitch_min: 0.95
  pitch_max: 1.57
  x_min: -0.21
  x_max: 0.22
  y_min: -0.30
  y_max: 0.30
  z_min: 0.745
  z_max: 1.5
- name: "Back Surface"
  remove_surface: true
  parent_frame_id: "base_footprint"
  child_frame_id: "camera_depth_frame"
  bounding_frame_id: "base_footprint"
  segmentation_frame_id: "map"
  roll_min: 2.00
  x_min: -1.25
  x_max: -0.36
  z_min: 0.20
